---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Update postfix to the latest version (if extra repositories enabled).
  yum: >
    name=postfix
    state=latest
    enablerepo={{ mysql_enablerepo }}
  when: mysql_enablerepo != ""

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Define instance strategy.
  set_fact: use_mysql_multi={{ mysql_multi|length > 0 }}

- include: "multi.yml"
  when: use_mysql_multi

- include: "single.yml"
  when: use_mysql_multi == "False"

# ex: ft=ansible et ts=2 sw=2:
