---
# This playbook deploys the application stack required for Open Vault

- name: Provision Open Vault webserver
  hosts: webservers
  remote_user: ec2-user

  roles:
    - role: gcc
      sudo: yes
    - role: gcc-c++
      sudo: yes
    - role: geerlingguy.ruby
      sudo: yes
      ruby_install_from_source: true
    - httpd
    - role: geerlingguy.git
      sudo: yes
    - role: geerlingguy.mysql
      sudo: yes
      mysql_packages:
        - mysql
        - mysql-server
        - mysql-devel
    - role: crushlovely.capistrano
      app_path: /var/www/openvault
      app_user: ec2-user
      app_group: ec2-user