---
# This playbook deploys the application stack required for Open Vault

- name: install webserver
  hosts: webservers
  remote_user: ec2-user

  roles:
    - httpd
    - geerlingguy.ruby
    - crushlovely.capistrano
    
  vars:
    app_path: /var/www/openvault
    app_user: ec2-user
    app_group: ec2-user