---
# This playbook deploys the application stack required for Open Vault

- name: install webserver
  hosts: webservers
  remote_user: ec2-user

  roles:
    - httpd
    - geerlingguy.ruby
    - role: geerlingguy.git
      sudo: yes
    - role: crushlovely.capistrano
      app_path: /var/www/openvault
      app_user: ec2-user
      app_group: ec2-user