---
# This playbook deploys the application stack required for Open Vault

- name: Install build tools
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: gcc, sudo: yes }
    - { role: gcc-c++, sudo: yes }

# Required for nokogiri gem install
- name: Install patch
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: patch, sudo: yes }

- name: Install ruby from source
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: geerlingguy.ruby, sudo: yes, ruby_install_from_source: true }

- name: Install apache webserver
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: httpd, sudo: yes }

- name: Install Git
  hosts: webservers
  remote_user: ec2-user
  roles:
  - { role: geerlingguy.git, sudo: yes }

# required for cleaning up default install of mysql
# using the geerlingguy.mysql role.
# - name: Install mysql-python module
#   hosts: webservers
#   remote_user: ec2-user
#   tasks:
#     - pip: "name=Mysql-python state=present"
#       sudo: yes

- name: Install MySQL
  hosts: webservers
  remote_user: ec2-user
  roles:
    - role: geerlingguy.mysql
      sudo: yes
      mysql_packages:
        - mysql
        - mysql-server
        - mysql-devel

- name: Configure server for Capistrano deployments
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: crushlovely.capistrano, app_path: /var/www/openvault,
        app_user: ec2-user, app_group: ec2-user }

- name: install the ruby racer
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - gem: "name=therubyracer state=present"
      sudo: yes