---
# This playbook deploys the application stack required for Open Vault

- name: Install build tools
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: gcc, sudo: yes }
    - { role: gcc-c++, sudo: yes }

# Required for nokogiri gem install
- name: Install patch
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: patch, sudo: yes }

- name: Install libcurl-devel
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - yum: name=libcurl-devel
      become: yes
      become_method: sudo
  tags:
    - libcurl-devel

- name: Install sqlite-devel
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - yum: name=sqlite-devel
      become: yes
      become_method: sudo
  tags:
    - sqlite-devel

- name: Install ruby from source
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: geerlingguy.ruby, sudo: yes, ruby_install_from_source: true }

- name: Install apache webserver
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: httpd, sudo: yes }

- name: Config apache virtual host
  hosts: webservers
  remote_user: ec2-user
  sudo: yes
  tasks:
    - file:
        state: directory
        path: /etc/httpd/sites-available
    - file:
        state: directory
        path: /etc/httpd/sites-enabled
    - template:
        src: templates/openvault.conf.j2
        dest: /etc/httpd/sites-available/openvault.conf
    - file:
        state: link
        src: /etc/httpd/sites-available/openvault.conf
        dest: /etc/httpd/sites-enabled/openvault.conf
    - lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: 'include \/etc\/httpd\/sites-enabled\/'
        line: "include /etc/httpd/sites-enabled/"
  tags:
    - apache-vhost-config

- name: Install Phusion Passenger
  hosts: webservers
  remote_user: ec2-user
  # needs path to ruby gem executables in /usr/local/bin
  environment:
    PATH: '{{ ansible_env.PATH }}:/usr/local/bin'
  roles:
    - { role: passenger, sudo: yes }
  tags:
    - passenger

- name: Install Git
  hosts: webservers
  remote_user: ec2-user
  roles:
  - { role: geerlingguy.git, sudo: yes }

- name: Configure server for Capistrano deployments
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: crushlovely.capistrano, app_path: /var/www/openvault,
        app_user: ec2-user, app_group: ec2-user }

- name: install the ruby racer
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - gem: "name=therubyracer state=present"
      sudo: yes