---
# This playbook deploys the application stack required for Boston Local TV

# - name: Install apache webserver
#   hosts: webservers
#   remote_user: ec2-user
#   roles:
#     - { role: httpd, become: yes }

- name: Config apache virtual host
  hosts: webservers
  remote_user: ec2-user
  become: yes
  tasks:
    - file:
        state: directory
        path: /etc/httpd/sites-available
    - file:
        state: directory
        path: /etc/httpd/sites-enabled
    - template:
        src: templates/bostonlocaltv.conf
        dest: /etc/httpd/sites-available/bostonlocaltv.conf
    - file:
        state: link
        src: /etc/httpd/sites-available/bostonlocaltv.conf
        dest: /etc/httpd/sites-enabled/bostonlocaltv.conf
    - lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: 'include \/etc\/httpd\/sites-enabled\/'
        line: "include /etc/httpd/sites-enabled/"
  tags:
    - apache-vhost-config

- name: configure logrotate for httpd and jettywrapper logs
  hosts: webservers
  remote_user: ec2-user
  become: true
  tasks:
    - template:
        src: templates/etc/logrotate.d/httpd
        dest: /etc/logrotate.d/httpd
    - template:
        src: templates/etc/logrotate.d/jettywrapper
        dest: /etc/logrotate.d/jettywrapper
    - template:
        src: templates/etc/cron.hourly/logrotate
        dest: /etc/cron.hourly/logrotate
        mode: 0755
  tags:
    - logrotate

- name: Install Git
  hosts: webservers
  remote_user: ec2-user
  roles:
  - { role: geerlingguy.git, become: yes }

# - name: Configure servers with ruby support for single user
#   hosts: webservers
#   remote_user: ec2-user
#   roles:
#     - { role: rvm.ruby,
#         tags: ruby,
#         rvm1_rubies: ['ruby-2.3.0'],
#         rvm1_user: 'ec2-user'
#       }
#   tags: rvm

- name: Create capistrano shared directories
  hosts: webservers
  remote_user: ec2-user
  tasks:
  - name: "Create document root, shared directory, and shared config directory"
    file: path=/var/www/bostonlocaltv/shared/config state=directory owner=ec2-user group=ec2-user force=yes
    become: yes
  tags:
    - capistrano

# - name: Install Phusion Passenger
#   hosts: webservers
#   remote_user: ec2-user
#   roles:
#     - { role: passenger, become: yes }
#   tags:
#     - passenger

# - name: install libxurl devle
#   hosts: webservers
#   remote_user: ec2-user
#   become: yes
#   tasks:
#   - yum:
#     name: libcurl-devel
#   tags:
#     - curl

- name: install libxurl devle
  hosts: webservers
  remote_user: ec2-user
  become: yes
  tasks:
  - yum:
    name: java-1.8.0-openjdk
  tags:
    - java

# sudo yum install java-1.8.0-openjdk


- name: install passeinger apach emodule
  hosts: webservers
  remote_user: ec2-user
  tasks:
  - shell: /home/ec2-user/.rvm/gems/ruby-2.3.0/wrappers/passenger-install-apache2-module --auto

# - name: install bundler gem
#   hosts: webservers
#   remote_user: ec2-user
#   tasks:
#   - gem:
#       name: bundler
#       user_install: no
#   tags:
#     - bundler

# - name: Bundle install
#   hosts: webservers
#   remote_user: ec2-user
#   tasks:
#   - bundler: 
#       state: present
#       chdir: /var/www/bostonlocaltv/current
#   tags:
#     - bundler

- name: restart httpd
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - service: name=httpd state=restarted enabled=yes
      become: yes

