---
# This playbook deploys the application stack required for Open Vault

- name: Install build tools
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: gcc, sudo: yes }
    - { role: gcc-c++, sudo: yes }

# Required for nokogiri gem install
- name: Install patch
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: patch, sudo: yes }

- name: Install libcurl-devel
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - yum: name=libcurl-devel
      become: yes
      become_method: sudo
  tags:
    - libcurl-devel

- name: Install sqlite-devel
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - yum: name=sqlite-devel
      become: yes
      become_method: sudo
  tags:
    - sqlite-devel

# Disabling in favor of RVM. TODO: remove this if RVM works.
# - name: Install ruby from source
#   hosts: webservers
#   remote_user: ec2-user
#   roles:
#     - { role: geerlingguy.ruby, sudo: yes, ruby_install_from_source: true }

# Borrowed from https://github.com/rvm/rvm1-ansible
- name: Configure servers with ruby support for single user
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.1'],
        rvm1_user: 'ec2-user'
      }
  tags:
      - rvm

- name: Install apache webserver
  hosts: webservers
  remote_user: ec2-user
  roles:
    - { role: httpd, sudo: yes }

- name: Config apache virtual host
  hosts: webservers
  remote_user: ec2-user
  sudo: yes
  tasks:
    - file:
        state: directory
        path: /etc/httpd/sites-available
    - file:
        state: directory
        path: /etc/httpd/sites-enabled
    - template:
        src: templates/phydo.conf
        dest: /etc/httpd/sites-available/phydo.conf
    - file:
        state: link
        src: /etc/httpd/sites-available/phydo.conf
        dest: /etc/httpd/sites-enabled/phydo.conf
    - lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: 'include \/etc\/httpd\/sites-enabled\/'
        line: "include /etc/httpd/sites-enabled/"
  tags:
    - apache-vhost-config

- name: Install Phusion Passenger
  hosts: webservers
  remote_user: ec2-user
  # needs path to ruby gem executables in /usr/local/bin
  environment:
    PATH: '{{ ansible_env.PATH }}:/usr/local/bin'
  roles:
    - { role: passenger, sudo: yes }
  tags:
    - passenger

- name: Install Git
  hosts: webservers
  remote_user: ec2-user
  roles:
  - { role: geerlingguy.git, sudo: yes }

- name: Create capistrano shared directories
  hosts: webservers
  remote_user: ec2-user
  tasks:
  - name: "Create document root, shared directory, and shared config directory"
    file: path=/var/www/phydo/shared/config state=directory owner=ec2-user group=ec2-user force=yes
    sudo: yes
  tags:
    - capistrano


- name: install the ruby racer
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - gem: "name=therubyracer state=present"
      sudo: yes
  tags:
    - therubyracer

- name: restart httpd
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - service: name=httpd state=restarted enabled=yes
      sudo: yes